version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: friends-stream-backend
    ports:
      - "3001:3001"
    volumes:
      - backend-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_PATH=/app/data/videos.db
    networks:
      - friends-stream-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/videos', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: friends-stream-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - friends-stream-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend-data:
    driver: local

networks:
  friends-stream-network:
    driver: bridge
